# Generated by Django 3.2.7 on 2022-06-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
