# Generated by Django 3.2.7 on 2022-06-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='current_user',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='users',
        ),
        migrations.RemoveField(
            model_name='image',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
